# Generated by Django 2.2.1 on 2020-02-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=20, verbose_name='邮箱')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('phone_num', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('gender', models.IntegerField(choices=[(0, '女'), (1, '男')], default=0, verbose_name='性别')),
                ('address', models.TextField(blank=True, null=True, verbose_name='地址')),
                ('createtime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('isDelete', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否删除')),
            ],
            options={
                'db_table': 'loginuser',
                'verbose_name_plural': '用户表',
            },
        ),
    ]
