# Generated by Django 2.2.1 on 2020-02-21 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_name', models.CharField(max_length=32, verbose_name='供应商名称')),
                ('sup_country', models.CharField(blank=True, max_length=32, null=True, verbose_name='供应商/国籍')),
                ('sup_province', models.CharField(blank=True, max_length=32, null=True, verbose_name='省/州')),
                ('sup_area', models.CharField(blank=True, max_length=32, null=True, verbose_name='区县')),
                ('sup_address', models.TextField(blank=True, max_length=32, null=True, verbose_name='具体地址')),
                ('sup_phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('sup_tel', models.CharField(blank=True, max_length=15, null=True, verbose_name='座机电话')),
                ('sup_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('sup_sex', models.IntegerField(choices=[(0, '女'), (1, '男')], default=0, verbose_name='性别')),
                ('sup_user', models.CharField(max_length=20, verbose_name='联系人')),
            ],
            options={
                'db_table': 'supplier',
                'verbose_name_plural': '供应商表',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goods_num', models.CharField(max_length=13, verbose_name='商品编号')),
                ('Goods_name', models.CharField(max_length=32, verbose_name='商品名称')),
                ('Goods_price', models.FloatField(verbose_name='商品单价')),
                ('Goods_count', models.IntegerField(verbose_name='商品数量')),
                ('Goods_location', models.CharField(max_length=32, verbose_name='商品产地')),
                ('Goods_safe_date', models.IntegerField(verbose_name='保质期(天)')),
                ('Goods_pro_date', models.DateTimeField(auto_now=True, verbose_name='生产日期')),
                ('Goods_status', models.IntegerField(choices=[(0, '在售'), (1, '停售')], default=0, verbose_name='商品状态')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginUser.Supplier')),
            ],
            options={
                'db_table': 'goods',
                'verbose_name_plural': '商品表',
            },
        ),
    ]
