# Generated by Django 2.2.1 on 2020-02-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0002_goods_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='sup_status',
            field=models.IntegerField(default=0, verbose_name='是否合作'),
        ),
    ]
