# Generated by Django 2.2.1 on 2020-02-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0003_supplier_sup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='Goods_inprice',
            field=models.FloatField(default=0, verbose_name='成本价'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goods',
            name='Goods_price',
            field=models.FloatField(verbose_name='销售单价'),
        ),
    ]
