# Generated by Django 2.2.1 on 2020-02-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0004_auto_20200221_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='sup_city',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='市'),
        ),
    ]
