# Generated by Django 2.2.1 on 2020-02-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0005_supplier_sup_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='sup_status',
            field=models.IntegerField(choices=[(0, '合作'), (1, '终止')], default=0, verbose_name='是否合作'),
        ),
    ]
