# Generated by Django 2.2.1 on 2020-02-21 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0006_auto_20200221_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginUser.Supplier', verbose_name='供应商'),
        ),
    ]
